name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update:
    name: Update Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Dependencies
        run: pip install -r ./requirements.txt
      - name: Update Data
        run: |
          cd script
          python download.py
      - name: Config Git
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Upload File
        run: |
          if [[ `git status --porcelain` ]]; then
            git add .
            git commit -m "Update Data"
            git push
          else
            echo Pass
          fi
  build:
    name: Page Build
    runs-on: ubuntu-latest
    needs: update
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Dependencies
        run: pip install -r ./requirements.txt
      - name: Page Build
        run: |
          cd script
          python main.py
      - name: Upload Artifacts
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: src/
  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
